version: '3'
services:
  mysql:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: src_development
      TZ: "Asia/Tokyo"
  rails:
    build: ./src
    tty: true
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/src
    environment:
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '443:443'
    links:
      - rails
    restart: always
    environment:
      DOMAINS: 'emp-test.localhost -> http://rails:3000'
      STAGE: 'local'
